import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'todo-list',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className=" flex justify-center items-center h-screen w-screen">
        {children}
      </body>
    </html>
  )
}
